{
 "title": "Synthetic Dashboard for Java Selenium Robot - PortalCheckMini",
 "tags": [
  "kazazoom",
  "portal",
  "robot",
  "influxdb"
 ],
 "time": { "from": "now-6h", "to": "now-1m" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "class",
    "label": "Selected Flow",
    "query": "SHOW TAG VALUES FROM testmethod WITH KEY=testclass"
   },
   {
    "name": "inter",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "check_duration",
    "label": "Last Checks Duration",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Checks the last 30mins all flow steps and returns NOT if any step FAILED. SKIPPED will return OK.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND (\"result\" = 'FAIL' )) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "FAIL" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" }
     ]
    }
   ]
  },
  {
   "title": "End to end",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "testmethod",
     "query": "SELECT sum(\"duration\")/1000 FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" }
     ]
    }
   ]
  },
  {
   "title": "End to end",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "testmethod",
     "query": "SELECT sum(\"duration\") FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" }
     ]
    }
   ]
  },
  {
   "title": "All Checks (# Passed)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") as \"Check\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND result = 'PASS') AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep08" }
     ]
    }
   ]
  },
  {
   "title": "Pass-o-Meter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01') AND $timeFilter GROUP BY result",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep08" }
     ]
    }
   ]
  },
  { "title": "Status (last 30mins)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "STEP 1: Open Website",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") FROM \"testmethod\" WHERE (\"result\" = 'PASS' AND \"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep08') AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep01" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "PASS" }
     ]
    }
   ]
  },
  {
   "title": "STEP 2: Login",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") FROM \"testmethod\" WHERE (\"result\" = 'PASS' AND \"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep08') AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep02" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "PASS" }
     ]
    }
   ]
  },
  {
   "title": "STEP 3: Open Board",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") FROM \"testmethod\" WHERE (\"result\" = 'PASS' AND \"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep08') AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep03" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "PASS" }
     ]
    }
   ]
  },
  {
   "title": "STEP 4: Create Card",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") FROM \"testmethod\" WHERE (\"result\" = 'PASS' AND \"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep08') AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep04" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "PASS" }
     ]
    }
   ]
  },
  {
   "title": "STEP 5: Edit Card",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") FROM \"testmethod\" WHERE (\"result\" = 'PASS' AND \"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep08') AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep05" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "PASS" }
     ]
    }
   ]
  },
  {
   "title": "STEP 6: Move Card",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") FROM \"testmethod\" WHERE (\"result\" = 'PASS' AND \"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep08') AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep06" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "PASS" }
     ]
    }
   ]
  },
  {
   "title": "STEP 7: Archive Card",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") FROM \"testmethod\" WHERE (\"result\" = 'PASS' AND \"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep08') AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep07" },
      { "condition": "AND", "key": "result", "operator": "=", "value": "PASS" }
     ]
    }
   ]
  },
  {
   "title": "Legend",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 12, "y": 7 },
   "options": {
    "content": "<font size=1pt>OK means last 3x test PASSED. NOK means one of last 3x tests FAILED or SKIPPED</font>"
   },
   "content": "<font size=1pt>OK means did not FAIL. Skipped is also OK.</font>",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "STEP 1: Website",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "alias": "$tag_result",
       "measurement": "testmethod",
       "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep01') AND $timeFilter GROUP BY result",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "result", "operator": "=", "value": "PASS" },
        { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "doStep03" }
       ]
      }
     ]
    },
    {
     "title": "STEP 2: Login",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "alias": "$tag_result",
       "measurement": "testmethod",
       "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep02') AND $timeFilter GROUP BY result",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "result", "operator": "=", "value": "PASS" },
        { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "doStep03" }
       ]
      }
     ]
    },
    {
     "title": "STEP 3: Enquiry",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "alias": "$tag_result",
       "measurement": "testmethod",
       "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep03') AND $timeFilter GROUP BY result",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "result", "operator": "=", "value": "PASS" },
        { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "doStep03" }
       ]
      }
     ]
    },
    {
     "title": "STEP 4: Object",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "alias": "$tag_result",
       "measurement": "testmethod",
       "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep04') AND $timeFilter GROUP BY result",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "result", "operator": "=", "value": "PASS" },
        { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "doStep03" }
       ]
      }
     ]
    },
    {
     "title": "STEP 5: Calculate",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "alias": "$tag_result",
       "measurement": "testmethod",
       "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep05') AND $timeFilter GROUP BY result",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "result", "operator": "=", "value": "PASS" },
        { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "doStep03" }
       ]
      }
     ]
    },
    {
     "title": "STEP 6: Go2Customer",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "alias": "$tag_result",
       "measurement": "testmethod",
       "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep06') AND $timeFilter GROUP BY result",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "result", "operator": "=", "value": "PASS" },
        { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "doStep03" }
       ]
      }
     ]
    },
    {
     "title": "STEP 7: Customer",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "alias": "$tag_result",
       "measurement": "testmethod",
       "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep07') AND $timeFilter GROUP BY result",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "result", "operator": "=", "value": "PASS" },
        { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "doStep03" }
       ]
      }
     ]
    },
    {
     "title": "STEP 8: Crefo",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "alias": "$tag_result",
       "measurement": "testmethod",
       "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep08') AND $timeFilter GROUP BY result",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "result", "operator": "=", "value": "PASS" },
        { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "doStep03" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "STEP 1: Website",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep01" }
     ]
    }
   ]
  },
  {
   "title": "STEP 2: Login",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep02" }
     ]
    }
   ]
  },
  {
   "title": "STEP 3: Open Board",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep03" }
     ]
    }
   ]
  },
  {
   "title": "STEP 4: Create Card",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep04" }
     ]
    }
   ]
  },
  {
   "title": "STEP 5: Edit Card",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep05" }
     ]
    }
   ]
  },
  {
   "title": "STEP 6: Move Card",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep06" }
     ]
    }
   ]
  },
  {
   "title": "STEP 7: Archive Card",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep07" }
     ]
    }
   ]
  },
  {
   "title": "Legend",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 15 },
   "options": {
    "content": "<p style=\"color:gray\">\nThis is a time graph per step of the synthetic test step.\n</p>\n\n\n\n"
   },
   "content": "<p style=\"color:gray\">\nThis is a time graph per step of the synthetic test.\n</p>\n\n\n\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Step Detail (Response Time)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Step 1 - Website",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep01" }
     ]
    }
   ]
  },
  {
   "title": "Pass-o-Meter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep01') AND $timeFilter GROUP BY result",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep08" }
     ]
    }
   ]
  },
  {
   "title": "Step 2 - Login",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep02" }
     ]
    }
   ]
  },
  {
   "title": "Pass-o-Meter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep02') AND $timeFilter GROUP BY result",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep08" }
     ]
    }
   ]
  },
  {
   "title": "Step 3 - Open Board",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep03" }
     ]
    }
   ]
  },
  {
   "title": "Pass-o-Meter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep03') AND $timeFilter GROUP BY result",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep08" }
     ]
    }
   ]
  },
  {
   "title": "Step 4 - Create Card",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep04" }
     ]
    }
   ]
  },
  {
   "title": "Pass-o-Meter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep04') AND $timeFilter GROUP BY result",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep08" }
     ]
    }
   ]
  },
  {
   "title": "Step 5 - Edit Card",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep05" }
     ]
    }
   ]
  },
  {
   "title": "Pass-o-Meter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep05') AND $timeFilter GROUP BY result",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep08" }
     ]
    }
   ]
  },
  {
   "title": "Step 6 - Move Card",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep06" }
     ]
    }
   ]
  },
  {
   "title": "Pass-o-Meter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep06') AND $timeFilter GROUP BY result",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep08" }
     ]
    }
   ]
  },
  {
   "title": "Step 7 - Archive Card",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "PASS" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep07" }
     ]
    }
   ]
  },
  {
   "title": "Pass-o-Meter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT count(\"duration\") as \"Count\" FROM \"testmethod\" WHERE (\"testclass\" = 'portalcheck.Trello_Flow01' AND \"name\" = 'doStep07') AND $timeFilter GROUP BY result",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "doStep08" }
     ]
    }
   ]
  },
  { "title": "Failure Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "FAILED a step",
   "type": "graph",
   "description": "A previous step failed",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "testmethod",
     "query": "SELECT \"duration\" FROM \"testmethod\" WHERE (\"result\" = 'FAIL' AND \"testclass\" = 'portalcheck.Trello_Flow01') AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "FAIL" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" }
     ]
    }
   ]
  },
  {
   "title": "Skipped a step",
   "type": "graph",
   "description": "A previous step failed",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "testmethod",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "SKIPPED" },
      { "condition": "AND", "key": "testclass", "operator": "=", "value": "portalcheck.Trello_Flow01" }
     ]
    }
   ]
  }
 ]
}